[package]
name = "pd_rw_imu"
version = "0.1.0"
edition = "2024"

[dependencies]
libm = "0.2.15"
nalgebra = { version = "0.34.1", default-features = false, features = ["libm"] }
#xdevs-no-std = { version = "0.3.0", features = ["std"] }
xdevs-no-std = { version = "0.3.0", features = ["embassy"] }

[features]
simulation = []
hardware = []
default = ["hardware"]